apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: m0at0wtya-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:f6dcf1d034ac4021a99071d0f26d2ab68fa3013b@sha256:685728a96ebc8470e83f8d04a4e455fac3fbb23f77f001ff90ae2ecef073f3e6
          name: container-image
